### ISSUE TITLE
Not reading data properly

### ISSUE THREAD

**Issue by benerbe20** [john30/ebusd-debian#11]
Hey y'all,
I need some help...

My setup looks as follow:

I have a Vaillant heating pump with an Esera rs232 Ebus-Coupler that is connected via a rs232-to-usb-converter to a raspberry pi.

It all works just fine with the data being transmitted to the RPI as it should. I already made sure that it is not a hardware problem by checking the raw tty port readings on the RPI which look legitimate.

The problem is that the ebus service when run does not convert the input data, even though it shows that it has a connection established and is receiving data.

<img width="721" alt="Bildschirm­foto 2023-04-09 um 18 47 07" src="https://user-images.githubusercontent.com/85848604/230785494-656197d0-fed0-4ff7-93af-fc0e625d2be7.png">

The webserver when checked does not show any useful readings other than some error/scan messages, it should rather be some system values:

`
{
 "broadcast": {
  "messages": {   "datetime": {
    "name": "datetime",
    "passive": true,
    "write": false,
    "lastup": 0
   },
   "error": {
    "name": "error",
    "passive": true,
    "write": false,
    "lastup": 0
   },
   "id-u": {
    "name": "id",
    "passive": true,
    "write": false,
    "lastup": 0
   },
   "signoflife": {
    "name": "signoflife",
    "passive": true,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.04": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.05": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.08": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.15": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 1680656189,
    "zz": 21,
    "decodeerror": "ERR: argument value out of valid range"
   }
  }
 },
 "scan.23": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.38": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.50": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.57": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.60": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.75": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.80": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.88": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.8b": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.ab": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.ae": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.ba": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.d5": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.ea": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "scan.f5": {
  "messages": {   "": {
    "name": "",
    "passive": false,
    "write": false,
    "lastup": 0
   }
  }
 },
 "global": {
  "version": "23.1.23.1",
  "updatecheck": "OK",
  "signal": true,
  "symbolrate": 30,
  "maxsymbolrate": 133,
  "minarbitrationmicros": 2,
  "maxarbitrationmicros": 74,
  "minsymbollatency": 2,
  "maxsymbollatency": 12,
  "qq": 49,
  "reconnects": 0,
  "masters": 8,
  "messages": 30,
  "lastup": 1680656189
 }
}
`

What I want is to read the ebus data that's being received and later on send some commands to the system as well...

Any help with my issues would be appreciated!

**Comment by john30** [comment]
wrong repo
