### ISSUE TITLE
Dependency libssl1.1 is depreciated

### ISSUE THREAD

**Issue by knalltuete86** [john30/ebusd-debian#12]
Installation of ebusd on Debian later than Bullseye (in my case Bookworm) fails due to missing dependency of libssl1.1 

Libssl1.1 is depreciated and will be replaced by libssl2 according to [https://packages.debian.org/bookworm/libs/libssl1.1](https://packages.debian.org/bookworm/libs/libssl1.1)

Regards

**Comment by knalltuete86** [comment]
Workaround to get ebusd working on Debian Bookworm:

Edit `/etc/apt/sources.list` and "downgrade" Sources to bullseye temporarily. e.g

`deb http://deb.debian.org/debian **bookworm** main contrib non-free non-free-firmware` to `deb http://deb.debian.org/debian **bullseye** main contrib non-free non-free-firmware`

Run `sudo apt update` and proceed according to installation instructions for Debian 11. Missing dependencies will be installed automatically.


Update of Dependencies to libssl3 should be considered.

**Comment by john30** [comment]
should be solved in next release with https://github.com/john30/ebusd/commit/8e55d44a14344d99a2802aea90a93551ac2a011e
