### ISSUE TITLE
apt exits with a key error

### ISSUE THREAD

**Issue by firewiremb** [john30/ebusd-debian#14]
pi@mypi:~ $ sudo apt update
OK:1 https://download.docker.com/linux/debian bookworm InRelease
Fehl:2 https://repo.ebusd.eu/apt/default/bookworm bookworm InRelease
  403  Forbidden [IP: 202.61.233.39 443]
OK:3 http://archive.raspberrypi.com/debian bookworm InRelease      
OK:4 http://deb.debian.org/debian bookworm InRelease            
OK:5 http://deb.debian.org/debian-security bookworm-security InRelease
OK:6 http://deb.debian.org/debian bookworm-updates InRelease
Paketlisten werden gelesen… Fertig
E: Fehlschlag beim Holen von https://repo.ebusd.eu/apt/default/bookworm/dists/bookworm/InRelease 403  Forbidden [IP: 202.61.233.39 443]
E: Das Depot »https://repo.ebusd.eu/apt/default/bookworm bookworm InRelease« ist nicht mehr signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

**Comment by john30** [comment]
can't reproduce
