### ISSUE TITLE
ebusd bookworm installation failed (no_pubkey)

### ISSUE THREAD

**Issue by SwissFanboy** [john30/ebusd-debian#16]
I have an RPi 4 with  Adapter Shield v5 on GPIO, Debian v11 (bullseye), EVCC and EBUSD on SD card. Worked fine. I was able to read out Vaillant ebus data.

Now I switch to SATA SSD via USB. To do this, I installed Debian v12 64-bit (bookworm) on SSD and then EVCC. Everything OK. Surplus loading works. Now I wanted to install EBUSD. I follow the README. 

- sudo mkdir -p /etc/apt/keyrings && sudo wget -q -O /etc/apt/keyrings/ebusd.gpg https://raw.githubusercontent.com/john30/ebusd-debian/master/ebusd.gpg
- sudo wget -O /etc/apt/sources.list.d/ebusd.list https://raw.githubusercontent.com/john30/ebusd-debian/master/ebusd-nomqtt-bookworm.list

But I get an error message when doing APT-GET UPDATE (NO_PUBKEY). What I am doing wrong? 
Does EVCC bother?  https://docs.evcc.io/docs/installation/linux 

![Screenshot 2024-11-03 095821](https://github.com/user-attachments/assets/8782569f-fe32-4c16-b46c-568955f751d2)

**Comment by El-Omari** [comment]
Hi, I got the same error. How did you resolve your problem?

Thanks

**Comment by SwissFanboy** [comment]
I switched back to Bullseye .... so everything works fine

**Comment by El-Omari** [comment]
Thanks, I resolve it too. I made the first instructions under a normal user with sudo option, I switch to “sudo su” and made the rest of instructions “apt-get ….. “ and this works for me.

**Comment by SwissFanboy** [comment]
With just "sudo su" it doesn't work for me. But with this chain of commands:
1) sudo su
2) wget -qO - https://raw.githubusercontent.com/john30/ebusd-debian/master/ebusd.gpg.key|sudo apt-key add -
![image](https://github.com/user-attachments/assets/00eb9c5e-4f03-4a12-8247-f7f5a07cc758)
3) mkdir -p /etc/apt/keyrings && wget -q -O /etc/apt/keyrings/ebusd.gpg https://raw.
githubusercontent.com/john30/ebusd-debian/master/ebusd.gpg
4) wget -O /etc/apt/sources.list.d/ebusd.list https://raw.githubusercontent.com/john30/ebusd-debian/master/ebusd-default-bookworm.list
5) apt update
![image](https://github.com/user-attachments/assets/cbe84613-3066-4e5d-afd8-03e58bc97037)
6) apt install ebusd

**Comment by El-Omari** [comment]
Just do these instructions:
1. sudo mkdir -p /etc/apt/keyrings && sudo wget -q -O /etc/apt/keyrings/ebusd.gpg https://raw.githubusercontent.com/john30/ebusd-debian/master/ebusd.gpg
2. 
sudo wget -O /etc/apt/sources.list.d/ebusd.list https://raw.githubusercontent.com/john30/ebusd-debian/master/ebusd-nomqtt-bookworm.list

Then change with 
3. sudo su
4. apt update
5. apt install ebusd


Let me know if it works for you.

**Comment by devachnid** [comment]
I've had the same problem, it was resolved by updating /etc/apt/sources.list.d/ebusd.list to
`deb [signed-by=/etc/apt/keyrings/ebusd.gpg] https://repo.ebusd.eu/apt/default/bookworm bookworm main`
