### ISSUE TITLE
How to log Date of all command passing on the ebus

### ISSUE THREAD

**Issue by dirkdecoppel** [john30/ebusd-debian#2]
Hello John,
Now the Ebus deamon is back working on my RPi Zero wifi i have following question:

How can i log all commands passing on the ebus?

Why i ask this question?
I have only basic knowledge of RPi & programming in Python.
Already 1 year i follow evening courses to improve my knowledge.
In the meantime learned a lot about programming in Python & Node-Red on Rpi-3
From next January i will be in the course where we can do our own Project.
My project could be programming a thermostat on Rpi.
For that i have right now in temporaly lean a Bulex Migo thermostat.
From this thermostat i want to understand all command send & received to my Bulex Heater.
So before connecting the Migo Thermostat on the Ebus i want to be shure to be able to log all data on the ebus. 
If possible in Hex format en with date-time log at the beginning of each line with command.

Thanks in advance for your help.
Dirk

**Comment by john30** [comment]
totally off-topic here. see the [ebusd wiki](https://github.com/john30/ebusd/wiki), especially [listen command](https://github.com/john30/ebusd/wiki/3.1.-TCP-client-commands#listen) and [raw logging options](https://github.com/john30/ebusd/wiki/2.-Run#raw-logging-options)
