### ISSUE TITLE
Systemd restarts ebusd all the time

### ISSUE THREAD

**Issue by JensJordan** [john30/ebusd-debian#3]
Hello John,
after manuel Installation of ebusd, I start the daemon via command line:
`sudo /usr/bin/ebusd -d /dev/ttyUSB0 --enablehex --scanconfig= -f -p 8888`
and it works like a charm (thanks for the good work).

But starting via `sudo systemctl start ebusd.service` does not returns:
After a short while, I must use Ctrl-C to exit from systemctl.

If I check the status of ebusd by using `sudo systemctl status ebusd.service`,
I can see that systemd restarts ebusd after ca. 2 minutes (all the time).

Maybe changing the daemon from `Type=forking` to `Type=simple` will solve the issue.

`OS-Release: "Raspbian GNU/Linux 10 (buster)"`

**Comment by john30** [comment]
you should check the log file of the system and ebusd first. this sounds a bit like an access problem to either the USB serial device or the logging folder or something else.

**Comment by JensJordan** [comment]
It was a copy & paste issue in my `EBUSD_OPTS`. I have used the config from csowada (eBUSd): `-d /dev/ttyUSB1 --enablehex --scanconfig= -f -p 8888`. Of cause, the `-f` was the problem.
