### ISSUE TITLE
Update says its already latest version

### ISSUE THREAD

**Issue by stephan1827** [john30/ebusd-debian#4]
root@raspberrypi:/home/pi# apt-get install ebusd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ebusd is already the newest version (3.3).
The following packages were automatically installed and are no longer required:
  alsa-base gstreamer0.10-alsa gstreamer0.10-plugins-base libdrm-etnaviv1 libgstreamer-plugins-base0.10-0 libgstreamer0.10-0
  libllvm6.0 libmicrodns0 libva-wayland2 libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-2 pimixer point-rpi
  python3-pyperclip rpi-eeprom-images xfconf
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by john30** [comment]
should be fine now
