### ISSUE TITLE
apt-get update fails 

### ISSUE THREAD

**Issue by erw111n** [john30/ebusd-debian#8]
I try to update ebusd and it
`apt-get update`
fails with:
`Err:5 https://repo.ebusd.eu/apt/default/buster buster Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 202.61.232.73 443]
.........
Reading package lists... Done
E: The repository 'https://repo.ebusd.eu/apt/default/buster buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
`
i did all the steps in the readme.md
the procedure worked before, when i updated last year to V21.2
thanks for yr. support!
erwin

**Comment by john30** [comment]
can't reproduce. maybe a temporary error? please try again

**Comment by erw111n** [comment]
well... not a temporary error, i would consider this as my user error,....
I never did a apt-get upgrade since i installed ebusd (2019/2020?) - so something in the cert-chain failed....
After doing apt-get upgrade, the apt-get update runs OK for ebusd-debian package !!!
Thanks for pointing me in the right direction....

**Comment by john30** [comment]
ok great
